tasks:
  - init: npm install
    command: 'echo "start server"'
vscode:
  extensions:
    - ritwickdey.LiveServer@5.6.1:5Mhl1RgVVDcIym163x8r+w==
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==